### PR TITLE
Added *.pyc files to .gitignore

### LINKED ISSUE #4: Unnecessary files in repo
It's not necessary to store *.pyc files in the repository

### PR DESCRIPTION
**Pull request by alexandr7035**
Fixes #4

### CODE REVIEW

**Comment by NeverBehave** [comment]
.gitignore was not changed in the pr

**Comment by alexandr7035** [comment]
Now it's OK)

**Comment by alexandr7035** [comment]
**Thanks!** That was  my first PQ)

**Comment by NeverBehave** [comment]
> **Thanks!** That was my first PQ)

We call it PR :)

**Pull request merged**
